### ISSUE TITLE
template.parameters duplicates a parameter used twice

### ISSUE THREAD

**Issue by DrPaulBrewer** [datavis-tech/json-templates#15]
Use case:  Specifying repetitive parameters to a certain cloud provider.  Below "foo" might be a disk, 
and "bar" a VM or a network adapter.  I am using json-templates so that I don't have to specify certain
things, like project or zone or region, over and over.  This seems to work, but I have to de-duplicate .parameters.

Test case;  There are duplicate formal parameters that should be replaced consistently
with the actual parameters.  They are indeed replaced consistently.  But, the list of parameters is duplicated on `tmpl.parameters`

    var jt = require("json-templates"); 
    var obj = { foo: "/region/{{region}}/zone/{{zone}}/foo", bar: "/region/{{region}}/zone/{{zone}}/bar" };
    var tmpl = jt(obj);
    console.log(tmpl.parameters);
    // with json-templates 1.8.0 parameters returns 4 parameters not 2
    console.log(tmpl({region: 'us-east3', zone: 'us-east3-c' }));
   // the template output looks correct

**Comment by curran** [comment]
@DrPaulBrewer Interesting discovery! Thank you for filing the issue.

I would warmly welcome an implementation proposal or Pull Request for this.

I suspect we just need to identify a place where we can add a bit of code that de-duplicates.

**Comment by DrPaulBrewer** [comment]
Here's a patch.  

I'd like to be able to include from npm instead of maintain a fork, so if you can get it into npm
soon I'd appreciate that.

**Comment by curran** [comment]
@DrPaulBrewer Thanks! Deployed the new version to NPM. https://github.com/datavis-tech/json-templates/releases/tag/v1.9.0

**Comment by DrPaulBrewer** [comment]
That's great. Happy New year.
