### ISSUE TITLE
Support objects on value replacing

### ISSUE THREAD

**Issue by javierblancosp** [datavis-tech/json-templates#17]
Hi, first of all good job for the module :).

We are using this for a complete different propose that the one you put on your readme and we need a little evolution on the code.

Currently the replacing of a hole object is not supported since the library replace the string with an stringify the context object.

Better with an example:

We have this json
```
const d = {
    s: '1',
    b:'{{c.d}}'
}
```
And this context:
```
const context = {
 d:{
    j:'a'
 }
}
```
As expected result we need this:
```
const d = {
    s: '1',
    b:{
      j:'a'
    }
}
```

Could we do a PR adding this behaviour? we believe that doing this will add the expected behaviour:
```
if(typeof match === 'object') {
  return match;
} else {
  return str.replace(match, value);
}
```
Also we are interested on move this to ES6.

Thanks :)

**Comment by curran** [comment]
Greetings @javierblancosp !

I would happily review and accept PRs for adding the feature you describe, and also porting to ES6.
