### ISSUE TITLE
Don't replace the non existent context keys by undefined

### ISSUE THREAD

**Issue by javierblancosp** [datavis-tech/json-templates#18]
Hi again,

Another functionality that could help us is, instead of replace the non existent keys on the context by undefined, in this case don't do the replacement. That way we can know easily what keys aren't on the context.

Example:

Json:
```
const d = {
    s: '1',
    b:'{{foo}}'
}
```

Context:
```
const c = {
   boo:'1',
   doo:'2'
}
```

Actual behaviour result:
```
const result = {
    s: '1',
    b:'undefined'
}
```

Expected behaviour:
```
const result  = {
    s: '1',
    b:'{{foo}}'
}
```
That sounds useful for you?

Thanks :)

**Comment by curran** [comment]
I'm not sure about this one. My gut reaction is that it seems a bit unintuitive as the default behavior.

Perhaps it would be best to have an option to turn on this behavior, rather than having it be the default?

**Comment by javierblancosp** [comment]
Yes maybe it's not to intuitive, then lets forget about this one :P
