### ISSUE TITLE
Compile code to ES5 to use with react-scripts

### ISSUE THREAD

**Issue by BrerBear** [datavis-tech/json-templates#24]
When using json-templates with react-scripts to produce a react app, build process fails to minify the source code.
```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/json-templates/index.js:11 
```
Here is the explanation from react-scripts vendor http://bit.ly/2tRViJ9

So that would be good if we have index.js compiled to ES5 before publishing npm.

Can you afford such a change?

**Comment by curran** [comment]
Ah yes, this is a great idea! I'm not at all opposed to transpiling to ES5, I just never faced the need.

I'd warmly welcome a Pull Request that does this.

I've had good experience using Rollup and Buble. These tools feel lighter weight than Babel & Webpack.

Here's an example configuration we may be able to use / copy - https://github.com/datavis-tech/topologica/blob/master/rollup.config.js

Would you be able to take a stab at a PR for this?

**Comment by BrerBear** [comment]
Sure. I can take care of it this weekend. Thanks!
