### ISSUE TITLE
Null value in data causes JavaScript error

### ISSUE THREAD

**Issue by CoryJ34** [datavis-tech/json-templates#28]
In this codesandbox: https://codesandbox.io/s/adoring-dan-6xw6g

There are two conditions that must be met in order for this error to occur:

1) There are multiple values referenced in one field (see "testField" in the code sample)
2) There is an actual null value (as opposed to the field being absent in the data, see "isNull" in the code sample) that occurs before a non-null value

It appears that the issue is related to https://github.com/datavis-tech/json-templates/pull/26 where only undefined values are checked, but not null.  Therefore, the defaultValue is not used and a null value is returned in the reduce function, leading to a "Cannot read property 'replace' of null" error in the next iteration of the reduce function because "str" is null.

**Comment by curran** [comment]
Nice! Thanks for this find. Would you mind crafting a failing test within the [existing test suite](https://github.com/datavis-tech/json-templates/blob/master/test.js) and opening a PR that includes the failing test? Thank you.

**Comment by CoryJ34** [comment]
https://github.com/datavis-tech/json-templates/pull/29

I added a test case and also included a possible fix for you to look over.

**Comment by curran** [comment]
Hooray! Thank you for this work. Merged the PR, added a note on this behavoir in the README, and released a new version.

As a side note, I would recommend to set an avatar for your GitHub profile, as then you will appear more professional in your online interactions.

**Comment by curran** [comment]
Hooray! Thank you for this work. Merged the PR, added a note on this behavoir in the README, and released a new version.

As a side note, I would recommend to set an avatar for your GitHub profile, as then you will appear more professional in your online interactions.

Thanks again for your work here. It's little improvements like this that help really solidify Open Source projects!

**Comment by Ashpabb** [comment]
Is this still open?

**Comment by curran** [comment]
Should have been closed back in July when that PR was merged. Closing now!

**Comment by mytharcher** [comment]
This error is not fully fixed, which case I have met is:

~~~js
import parse from 'json-templates';

const template = parse('{{a}} {{b}}');

console.log(template({ a: 0, b: 1 })); // '0 1': right
console.log(template({ a: null, b: null })); // null: emmm, maybe ' ' better, but acceptable

console.log(template({ a: null, b: 1 })); // Error: TypeError: Cannot read properties of null (reading 'replace')
~~~

If not provided the default value, and first variable is `null`, but the second is not, the error occurs.

**Comment by mytharcher** [comment]
I found another thing which is not so perfect is the default value will be applied on to `null`. The case I have met is like this:

```
expect(template('{{a}}')({ a: null })).toMatchObject({ a: null });
// got { a: undefined } which is not expected
```

This will cause some logic issue in usage, which `null` is not strict equal to `undefined`.

I will send another fix PR if needed.

**Comment by curran** [comment]
Oh nice! A PR with tests would be most welcome. Thank you.

**Comment by curran** [comment]
Closed by https://github.com/datavis-tech/json-templates/pull/45

Feel free to reopen if this comes up again.
