### ISSUE TITLE
support for JSON number as variables

### ISSUE THREAD

**Issue by alex-bluetrain** [datavis-tech/json-templates#30]
it's not possible to use json numbers as variable in the template without breaking the json format, 

**example**
```
{
    "name": "{user.name}",
    "age": {{user.age}}
}
```

when importing such file you get an `Unexpected token { in JSON at ...`

I could enclose the age value in doublequotes, but that will make it a string and violates the format I'm supposed to be compliant with. (HL7 FHIR objects)

**Comment by curran** [comment]
PRs welcome :)

**Comment by curran** [comment]
@alex-bluetrain Do you have any ideas for how to potentially solve this? I agree it would be a nice feature to have.

**Comment by curran** [comment]
I've added a failing test case for this here https://github.com/datavis-tech/json-templates/pull/32

**Comment by curran** [comment]
Nailed it! Released in https://github.com/datavis-tech/json-templates/releases/tag/v3.1.0
